import re
import unicodedata
from typing import Dict, Any
from dotenv import load_dotenv

load_dotenv()


def normalize_unicode(text: str) -> str:
    if not text:
        return ""
    return unicodedata.normalize("NFKC", text)


def basic_cleanup(text: str) -> str:
    if not text:
        return ""

    text = normalize_unicode(text)
    text = text.replace("\r", "\n")
    text = text.replace("\t", " ")

    # remove extra spaces
    text = re.sub(r"[ ]{2,}", " ", text)

    # normalize blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def remove_common_noise_lines(text: str) -> str:
    if not text:
        return ""

    junk_patterns = [
        r"^\s*page\s+\d+\s*$",
        r"^\s*copyright.*$",
        r"^\s*all rights reserved.*$",
        r"^\s*confidential.*$",
        r"^\s*www\..*$",
        r"^\s*http[s]?://.*$",
        r"^\s*click here.*$",
        r"^\s*generated by.*$",
    ]

    lines = text.split("\n")
    cleaned_lines = []

    for line in lines:
        line = line.strip()
        if not line:
            cleaned_lines.append("")
            continue

        skip = False
        for pattern in junk_patterns:
            if re.match(pattern, line, flags=re.IGNORECASE):
                skip = True
                break

        if not skip:
            cleaned_lines.append(line)

    return "\n".join(cleaned_lines).strip()


def preserve_structure(text: str) -> str:
    if not text:
        return ""

    # bullet normalization
    text = re.sub(r"\n?\s*[-•]\s*", "\n- ", text)

    # numbered list normalization
    text = re.sub(r"\n?\s*(\d+)\.\s*", r"\n\1. ", text)

    return text.strip()


# -------------------------
# TYPE-SPECIFIC CLEANERS
# -------------------------

def clean_pdf_text_record(text: str) -> str:
    text = basic_cleanup(text)

    # Remove page markers
    text = re.sub(r"(?im)^\s*[-–—]?\s*page\s+\d+\s*$", "", text)

    # Remove figure labels
    text = re.sub(r"(?im)^\s*figure\s+\d+[\-–—]?\s*\d*.*$", "", text)

    # Remove repeated dash-only lines
    text = re.sub(r"(?im)^\s*[-–—]{1,}\s*$", "", text)

    # Remove isolated broken short tokens like H / FAA / 19A lines
    lines = text.split("\n")
    cleaned_lines = []

    for line in lines:
        line = line.strip()

        if not line:
            cleaned_lines.append("")
            continue

        # remove super short broken lines unless meaningful
        if len(line) <= 2 and not re.search(r"\d", line):
            continue

        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines)

    # Remove common junk lines
    text = remove_common_noise_lines(text)

    # Remove excessive separators
    text = re.sub(r"[_\-]{5,}", "", text)

    # Normalize blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()

def clean_pdf_image_record(text: str) -> str:
    """
    For OCR or multimodal outputs from scanned/image PDFs.
    Preserve semantic summaries but reduce OCR mess.
    """
    text = basic_cleanup(text)
    text = remove_common_noise_lines(text)

    # remove super noisy OCR-like spacing
    text = re.sub(r"\s{2,}", " ", text)

    # collapse repeated punctuation
    text = re.sub(r"[.]{3,}", "...", text)

    return text.strip()


def clean_mdb_record(text: str) -> str:
    """
    For MDB rows flattened as pipe-separated values.
    Preserve row content and structure.
    """
    text = basic_cleanup(text)

    # normalize pipe spacing
    text = re.sub(r"\s*\|\s*", " | ", text)

    # remove repeated pipes
    text = re.sub(r"(\|\s*){2,}", " | ", text)

    return text.strip()


def clean_json_record(text: str) -> str:
    """
    For JSON-loaded text blobs.
    Keep semantic content, remove spacing noise.
    """
    text = basic_cleanup(text)
    text = preserve_structure(text)
    return text.strip()


def clean_generic_record(text: str) -> str:
    text = basic_cleanup(text)
    text = remove_common_noise_lines(text)
    text = preserve_structure(text)
    return text.strip()


def clean_record(record: Dict[str, Any]) -> Dict[str, Any]:
    """
    Clean one record based on file type and PDF subtype.
    Expects optional metadata:
      - file_type
      - extraction_method (optional): 'text', 'vision', 'ocr'
    """
    cleaned = dict(record)

    text = str(record.get("text", "") or "")
    file_type = str(record.get("file_type", "") or "").lower()
    extraction_method = str(record.get("extraction_method", "") or "").lower()

    if file_type == "pdf":
        if extraction_method in {"vision", "ocr", "image"}:
            cleaned["text"] = clean_pdf_image_record(text)
        else:
            cleaned["text"] = clean_pdf_text_record(text)

    elif file_type == "mdb":
        cleaned["text"] = clean_mdb_record(text)

    elif file_type == "json":
        cleaned["text"] = clean_json_record(text)

    else:
        cleaned["text"] = clean_generic_record(text)

    return cleaned

from openai import AzureOpenAI
import os

# init once
aoai_client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
)

DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")


def llm_clean_text(text: str) -> str:
    if not text or len(text.strip()) < 20:
        return text

    prompt = f"""
Clean the following document text for RAG usage.

Rules:
- Remove page numbers, headers, footers
- Remove forms, templates, empty labels
- Remove repeated words like 'SAMPLE', 'Plane Sense'
- Keep meaningful paragraphs, headings, lists
- Do NOT summarize
- Do NOT add new info
- Keep original meaning

TEXT:
{text}
"""

    try:
        response = aoai_client.chat.completions.create(
            model=DEPLOYMENT,
            messages=[
                {"role": "system", "content": "You clean extracted document text."},
                {"role": "user", "content": prompt}
            ],
            temperature=0
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        print(f"[LLM CLEAN ERROR] {e}")
        return text